version: '3'

services:
  csoapp:
    build: ./backend/
    restart: always
    command: sh -c "./wait-for-it.sh db:5432 -- python3 manage.py migrate && python3 ../app-data/data_init.py && uwsgi uwsgiconfig.ini"
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin1
      - DB_PASS=seismictoss613
      - DB_NAME=csodata
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: "admin1"
      POSTGRES_PASSWORD: "seismictoss613"
      POSTGRES_DB: "csodata"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

