# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cso_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Point',
            fields=[
                ('x_value', models.IntegerField()),
                ('y_value', models.IntegerField()),
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'data_point',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.TextField()),
                ('graph_name', models.TextField()),
                ('gender', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graph',
            },
        ),
        migrations.AddField(
            model_name='data_point',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cso_api.Graph'),
        ),
    ]
